pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/chinazagideon/alx-backend-python.git'
                }
            }
        }
        stage('Build and Test') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
                sh 'pytest --junitxml=reports/tests.xml'
            }
        }

        stage('Build and Push') {
            steps {
                sh 'docker build -t bill25concept/django-message-app:latest .'
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                    sh 'docker push bill25concept/django-message-app:latest'
                }
            }
        }
    }
}
