name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: messaging_app
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=10s --health-timeout=5s --health-retries=10
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install Dependencies
      run: pip3 install -r messaging_app/requirements.txt
      
    - name: Run Tests and Generate Coverage
      run: |
        pip3 install coverage
        pytest --junitxml=reports/tests.xml --cov=.
        coverage xml
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
          name: coverage-report
          path: coverage.xml

  lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
   
        - name: Install Flake8
          run: pip3 install flake8
          
        - name: Run Flake8
          run: flake8 .    
