pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t bill25concept/django-message-app:latest . '
            }
        }
        stage ('Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                    sh 'docker push $DOCKER_USERNAME/django-message-app:latest'
                }
            }
        }
    }
}
