apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django-messaging-app
    version: blue
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP